name: Publish package Bintray
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish package
        run: |
          cd src
          cd visage
          gradle clean build publish
        env:
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
